package com.example.ar_realestate;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;

public class CitiesAndTownInsert {

    static int lastCityId;
    public CitiesAndTownInsert() {
    }
    public void insertCity(){
        int counter=0;
        MainActivity.database.onCreate(MainActivity.db);
        Cursor cursor=MainActivity.db.rawQuery("SELECT * FROM Cities",null);
        cursor.moveToFirst();
        while (cursor.isAfterLast()==false){
            counter++;
            lastCityId=Integer.parseInt(cursor.getString(0));
            cursor.moveToNext();
        }
        if(lastCityId!=81) {
            String sqlQuery = "INSERT INTO Cities (CityName)VALUES\n" +
                    "('ADANA'),\n" +
                    "('ADIYAMAN'),\n" +
                    "('AFYON'),\n" +
                    "('AĞRI'),\n" +
                    "('AMASYA'),\n" +
                    "('ANKARA'),\n" +
                    "('ANTALYA'),\n" +
                    "('ARTVİN'),\n" +
                    "('AYDIN'),\n" +
                    "('BALIKESİR'),\n" +
                    "('BİLECİK'),\n" +
                    "('BİNGÖL'),\n" +
                    "('BİTLİS'),\n" +
                    "('BOLU'),\n" +
                    "('BURDUR'),\n" +
                    "('BURSA'),\n" +
                    "('ÇANAKKALE'),\n" +
                    "('ÇANKIRI'),\n" +
                    "('ÇORUM'),\n" +
                    "('DENİZLİ'),\n" +
                    "('DİYARBAKIR'),\n" +
                    "('EDİRNE'),\n" +
                    "('ELAZIĞ'),\n" +
                    "('ERZİNCAN'),\n" +
                    "('ERZURUM'),\n" +
                    "('ESKİŞEHİR'),\n" +
                    "('GAZİANTEP'),\n" +
                    "('GİRESUN'),\n" +
                    "('GÜMÜŞHANE'),\n" +
                    "('HAKKARİ'),\n" +
                    "('HATAY'),\n" +
                    "('ISPARTA'),\n" +
                    "('İÇEL'),\n" +
                    "('İSTANBUL'),\n" +
                    "('İZMİR'),\n" +
                    "('KARS'),\n" +
                    "('KASTAMONU'),\n" +
                    "('KAYSERİ'),\n" +
                    "('KIRKLARELİ'),\n" +
                    "('KIRŞEHİR'),\n" +
                    "('KOCAELİ'),\n" +
                    "('KONYA'),\n" +
                    "('KÜTAHYA'),\n" +
                    "('MALATYA'),\n" +
                    "('MANİSA'),\n" +
                    "('KAHRAMANMARAŞ'),\n" +
                    "('MARDİN'),\n" +
                    "('MUĞLA'),\n" +
                    "('MUŞ'),\n" +
                    "('NEVŞEHİR'),\n" +
                    "('NİĞDE'),\n" +
                    "('ORDU'),\n" +
                    "('RİZE'),\n" +
                    "('SAKARYA'),\n" +
                    "('SAMSUN'),\n" +
                    "('SİİRT'),\n" +
                    "('SİNOP'),\n" +
                    "('SİVAS'),\n" +
                    "('TEKİRDAĞ'),\n" +
                    "('TOKAT'),\n" +
                    "('TRABZON'),\n" +
                    "('TUNCELİ'),\n" +
                    "('ŞANLIURFA'),\n" +
                    "('UŞAK'),\n" +
                    "('VAN'),\n" +
                    "('YOZGAT'),\n" +
                    "('ZONGULDAK'),\n" +
                    "('AKSARAY'),\n" +
                    "('BAYBURT'),\n" +
                    "('KARAMAN'),\n" +
                    "('KIRIKKALE'),\n" +
                    "('BATMAN'),\n" +
                    "('ŞIRNAK'),\n" +
                    "('BARTIN'),\n" +
                    "('ARDAHAN'),\n" +
                    "('IĞDIR'),\n" +
                    "('YALOVA'),\n" +
                    "('KARABÜK'),\n" +
                    "('KİLİS'),\n" +
                    "('OSMANİYE'),\n" +
                    "('DÜZCE')";
            MainActivity.db.execSQL(sqlQuery);

            String sqlQueryDistrict ="INSERT INTO District (DistrictName, CityId) VALUES \n" +
                    "('ALADAĞ',1),\n" +
                    "('CEYHAN',1),\n" +
                    "('ÇUKUROVA',1),\n" +
                    "('FEKE',1),\n" +
                    "('İMAMOĞLU',1),\n" +
                    "('KARAİSALI',1),\n" +
                    "('KARATAŞ',1),\n" +
                    "('KOZAN',1),\n" +
                    "('POZANTI',1),\n" +
                    "('SAİMBEYLİ',1),\n" +
                    "('SARIÇAM',1),\n" +
                    "('SEYHAN',1),\n" +
                    "('TUFANBEYLİ',1),\n" +
                    "('YUMURTALIK',1),\n" +
                    "('YÜREĞİR',1),\n" +
                    "('BESNİ',2),\n" +
                    "('ÇELİKHAN',2),\n" +
                    "('GERGER',2),\n" +
                    "('GÖLBAŞI',2),\n" +
                    "('KAHTA',2),\n" +
                    "('MERKEZ',2),\n" +
                    "('SAMSAT',2),\n" +
                    "('SİNCİK',2),\n" +
                    "('TUT',2),\n" +
                    "('BAŞMAKÇI',3),\n" +
                    "('BAYAT',3),\n" +
                    "('BOLVADİN',3),\n" +
                    "('ÇAY',3),\n" +
                    "('ÇOBANLAR',3),\n" +
                    "('DAZKIRI',3),\n" +
                    "('DİNAR',3),\n" +
                    "('EMİRDAĞ',3),\n" +
                    "('EVCİLER',3),\n" +
                    "('HOCALAR',3),\n" +
                    "('İHSANİYE',3),\n" +
                    "('İSCEHİSAR',3),\n" +
                    "('KIZILÖREN',3),\n" +
                    "('MERKEZ',3),\n" +
                    "('SANDIKLI',3),\n" +
                    "('SİNANPAŞA',3),\n" +
                    "('SULTANDAĞI',3),\n" +
                    "('ŞUHUT',3),\n" +
                    "('DİYADİN',4),\n" +
                    "('DOĞUBAYAZIT',4),\n" +
                    "('ELEŞKİRT',4),\n" +
                    "('HAMUR',4),\n" +
                    "('MERKEZ',4),\n" +
                    "('PATNOS',4),\n" +
                    "('TAŞLIÇAY',4),\n" +
                    "('TUTAK',4),\n" +
                    "('AĞAÇÖREN',68),\n" +
                    "('ESKİL',68),\n" +
                    "('GÜLAĞAÇ',68),\n" +
                    "('GÜZELYURT',68),\n" +
                    "('MERKEZ',68),\n" +
                    "('ORTAKÖY',68),\n" +
                    "('SARIYAHŞİ',68),\n" +
                    "('SULTANHANI',68),\n" +
                    "('GÖYNÜCEK',5),\n" +
                    "('GÜMÜŞHACIKÖY',5),\n" +
                    "('HAMAMÖZÜ',5),\n" +
                    "('MERKEZ',5),\n" +
                    "('MERZİFON',5),\n" +
                    "('SULUOVA',5),\n" +
                    "('TAŞOVA',5),\n" +
                    "('AKYURT',6),\n" +
                    "('ALTINDAĞ',6),\n" +
                    "('AYAŞ',6),\n" +
                    "('BALA',6),\n" +
                    "('BEYPAZARI',6),\n" +
                    "('ÇAMLIDERE',6),\n" +
                    "('ÇANKAYA',6),\n" +
                    "('ÇUBUK',6),\n" +
                    "('ELMADAĞ',6),\n" +
                    "('ETİMESGUT',6),\n" +
                    "('EVREN',6),\n" +
                    "('GÖLBAŞI',6),\n" +
                    "('GÜDÜL',6),\n" +
                    "('HAYMANA',6),\n" +
                    "('KAHRAMANKAZAN',6),\n" +
                    "('KALECİK',6),\n" +
                    "('KEÇİÖREN',6),\n" +
                    "('KIZILCAHAMAM',6),\n" +
                    "('MAMAK',6),\n" +
                    "('NALLIHAN',6),\n" +
                    "('POLATLI',6),\n" +
                    "('PURSAKLAR',6),\n" +
                    "('SİNCAN',6),\n" +
                    "('ŞEREFLİKOÇHİSAR',6),\n" +
                    "('YENİMAHALLE',6),\n" +
                    "('AKSEKİ',7),\n" +
                    "('AKSU',7),\n" +
                    "('ALANYA',7),\n" +
                    "('DEMRE',7),\n" +
                    "('DÖŞEMEALTI',7),\n" +
                    "('ELMALI',7),\n" +
                    "('FİNİKE',7),\n" +
                    "('GAZİPAŞA',7),\n" +
                    "('GÜNDOĞMUŞ',7),\n" +
                    "('İBRADI',7),\n" +
                    "('KAŞ',7),\n" +
                    "('KEMER',7),\n" +
                    "('KEPEZ',7),\n" +
                    "('KONYAALTI',7),\n" +
                    "('KORKUTELİ',7),\n" +
                    "('KUMLUCA',7),\n" +
                    "('MANAVGAT',7),\n" +
                    "('MURATPAŞA',7),\n" +
                    "('SERİK',7),\n" +
                    "('ÇILDIR',75),\n" +
                    "('DAMAL',75),\n" +
                    "('GÖLE',75),\n" +
                    "('HANAK',75),\n" +
                    "('MERKEZ',75),\n" +
                    "('POSOF',75),\n" +
                    "('ARDANUÇ',8),\n" +
                    "('ARHAVİ',8),\n" +
                    "('BORÇKA',8),\n" +
                    "('HOPA',8),\n" +
                    "('KEMALPAŞA',8),\n" +
                    "('MERKEZ',8),\n" +
                    "('MURGUL',8),\n" +
                    "('ŞAVŞAT',8),\n" +
                    "('YUSUFELİ',8),\n" +
                    "('BOZDOĞAN',9),\n" +
                    "('BUHARKENT',9),\n" +
                    "('ÇİNE',9),\n" +
                    "('DİDİM',9),\n" +
                    "('EFELER',9),\n" +
                    "('GERMENCİK',9),\n" +
                    "('İNCİRLİOVA',9),\n" +
                    "('KARACASU',9),\n" +
                    "('KARPUZLU',9),\n" +
                    "('KOÇARLI',9),\n" +
                    "('KÖŞK',9),\n" +
                    "('KUŞADASI',9),\n" +
                    "('KUYUCAK',9),\n" +
                    "('NAZİLLİ',9),\n" +
                    "('SÖKE',9),\n" +
                    "('SULTANHİSAR',9),\n" +
                    "('YENİPAZAR',9),\n" +
                    "('ALTIEYLÜL',10),\n" +
                    "('AYVALIK',10),\n" +
                    "('BALYA',10),\n" +
                    "('BANDIRMA',10),\n" +
                    "('BİGADİÇ',10),\n" +
                    "('BURHANİYE',10),\n" +
                    "('DURSUNBEY',10),\n" +
                    "('EDREMİT',10),\n" +
                    "('ERDEK',10),\n" +
                    "('GÖMEÇ',10),\n" +
                    "('GÖNEN',10),\n" +
                    "('HAVRAN',10),\n" +
                    "('İVRİNDİ',10),\n" +
                    "('KARESİ',10),\n" +
                    "('KEPSUT',10),\n" +
                    "('MANYAS',10),\n" +
                    "('MARMARA',10),\n" +
                    "('SAVAŞTEPE',10),\n" +
                    "('SINDIRGI',10),\n" +
                    "('SUSURLUK',10),\n" +
                    "('AMASRA',74),\n" +
                    "('KURUCAŞİLE',74),\n" +
                    "('MERKEZ',74),\n" +
                    "('ULUS',74),\n" +
                    "('BEŞİRİ',72),\n" +
                    "('GERCÜŞ',72),\n" +
                    "('HASANKEYF',72),\n" +
                    "('KOZLUK',72),\n" +
                    "('MERKEZ',72),\n" +
                    "('SASON',72),\n" +
                    "('AYDINTEPE',69),\n" +
                    "('DEMİRÖZÜ',69),\n" +
                    "('MERKEZ',69),\n" +
                    "('BOZÜYÜK',11),\n" +
                    "('GÖLPAZARI',11),\n" +
                    "('İNHİSAR',11),\n" +
                    "('MERKEZ',11),\n" +
                    "('OSMANELİ',11),\n" +
                    "('PAZARYERİ',11),\n" +
                    "('SÖĞÜT',11),\n" +
                    "('YENİPAZAR',11),\n" +
                    "('ADAKLI',12),\n" +
                    "('GENÇ',12),\n" +
                    "('KARLIOVA',12),\n" +
                    "('KİĞI',12),\n" +
                    "('MERKEZ',12),\n" +
                    "('SOLHAN',12),\n" +
                    "('YAYLADERE',12),\n" +
                    "('YEDİSU',12),\n" +
                    "('ADİLCEVAZ',13),\n" +
                    "('AHLAT',13),\n" +
                    "('GÜROYMAK',13),\n" +
                    "('HİZAN',13),\n" +
                    "('MERKEZ',13),\n" +
                    "('MUTKİ',13),\n" +
                    "('TATVAN',13),\n" +
                    "('DÖRTDİVAN',14),\n" +
                    "('GEREDE',14),\n" +
                    "('GÖYNÜK',14),\n" +
                    "('KIBRISCIK',14),\n" +
                    "('MENGEN',14),\n" +
                    "('MERKEZ',14),\n" +
                    "('MUDURNU',14),\n" +
                    "('SEBEN',14),\n" +
                    "('YENİÇAĞA',14),\n" +
                    "('AĞLASUN',15),\n" +
                    "('ALTINYAYLA',15),\n" +
                    "('BUCAK',15),\n" +
                    "('ÇAVDIR',15),\n" +
                    "('ÇELTİKÇİ',15),\n" +
                    "('GÖLHİSAR',15),\n" +
                    "('KARAMANLI',15),\n" +
                    "('KEMER',15),\n" +
                    "('MERKEZ',15),\n" +
                    "('TEFENNİ',15),\n" +
                    "('YEŞİLOVA',15),\n" +
                    "('BÜYÜKORHAN',16),\n" +
                    "('GEMLİK',16),\n" +
                    "('GÜRSU',16),\n" +
                    "('HARMANCIK',16),\n" +
                    "('İNEGÖL',16),\n" +
                    "('İZNİK',16),\n" +
                    "('KARACABEY',16),\n" +
                    "('KELES',16),\n" +
                    "('KESTEL',16),\n" +
                    "('MUDANYA',16),\n" +
                    "('MUSTAFAKEMALPAŞA',16),\n" +
                    "('NİLÜFER',16),\n" +
                    "('ORHANELİ',16),\n" +
                    "('ORHANGAZİ',16),\n" +
                    "('OSMANGAZİ',16),\n" +
                    "('YENİŞEHİR',16),\n" +
                    "('YILDIRIM',16),\n" +
                    "('AYVACIK',17),\n" +
                    "('BAYRAMİÇ',17),\n" +
                    "('BİGA',17),\n" +
                    "('BOZCAADA',17),\n" +
                    "('ÇAN',17),\n" +
                    "('ECEABAT',17),\n" +
                    "('EZİNE',17),\n" +
                    "('GELİBOLU',17),\n" +
                    "('GÖKÇEADA',17),\n" +
                    "('LAPSEKİ',17),\n" +
                    "('MERKEZ',17),\n" +
                    "('YENİCE',17),\n" +
                    "('ATKARACALAR',18),\n" +
                    "('BAYRAMÖREN',18),\n" +
                    "('ÇERKEŞ',18),\n" +
                    "('ELDİVAN',18),\n" +
                    "('ILGAZ',18),\n" +
                    "('KIZILIRMAK',18),\n" +
                    "('KORGUN',18),\n" +
                    "('KURŞUNLU',18),\n" +
                    "('MERKEZ',18),\n" +
                    "('ORTA',18),\n" +
                    "('ŞABANÖZÜ',18),\n" +
                    "('YAPRAKLI',18),\n" +
                    "('ALACA',19),\n" +
                    "('BAYAT',19),\n" +
                    "('BOĞAZKALE',19),\n" +
                    "('DODURGA',19),\n" +
                    "('İSKİLİP',19),\n" +
                    "('KARGI',19),\n" +
                    "('LAÇİN',19),\n" +
                    "('MECİTÖZÜ',19),\n" +
                    "('MERKEZ',19),\n" +
                    "('OĞUZLAR',19),\n" +
                    "('ORTAKÖY',19),\n" +
                    "('OSMANCIK',19),\n" +
                    "('SUNGURLU',19),\n" +
                    "('UĞURLUDAĞ',19),\n" +
                    "('ACIPAYAM',20),\n" +
                    "('BABADAĞ',20),\n" +
                    "('BAKLAN',20),\n" +
                    "('BEKİLLİ',20),\n" +
                    "('BEYAĞAÇ',20),\n" +
                    "('BOZKURT',20),\n" +
                    "('BULDAN',20),\n" +
                    "('ÇAL',20),\n" +
                    "('ÇAMELİ',20),\n" +
                    "('ÇARDAK',20),\n" +
                    "('ÇİVRİL',20),\n" +
                    "('GÜNEY',20),\n" +
                    "('HONAZ',20),\n" +
                    "('KALE',20),\n" +
                    "('MERKEZEFENDİ',20),\n" +
                    "('PAMUKKALE',20),\n" +
                    "('SARAYKÖY',20),\n" +
                    "('SERİNHİSAR',20),\n" +
                    "('TAVAS',20),\n" +
                    "('BAĞLAR',21),\n" +
                    "('BİSMİL',21),\n" +
                    "('ÇERMİK',21),\n" +
                    "('ÇINAR',21),\n" +
                    "('ÇÜNGÜŞ',21),\n" +
                    "('DİCLE',21),\n" +
                    "('EĞİL',21),\n" +
                    "('ERGANİ',21),\n" +
                    "('HANİ',21),\n" +
                    "('HAZRO',21),\n" +
                    "('KAYAPINAR',21),\n" +
                    "('KOCAKÖY',21),\n" +
                    "('KULP',21),\n" +
                    "('LİCE',21),\n" +
                    "('SİLVAN',21),\n" +
                    "('SUR',21),\n" +
                    "('YENİŞEHİR',21),\n" +
                    "('AKÇAKOCA',81),\n" +
                    "('CUMAYERİ',81),\n" +
                    "('ÇİLİMLİ',81),\n" +
                    "('GÖLYAKA',81),\n" +
                    "('GÜMÜŞOVA',81),\n" +
                    "('KAYNAŞLI',81),\n" +
                    "('MERKEZ',81),\n" +
                    "('YIĞILCA',81),\n" +
                    "('ENEZ',22),\n" +
                    "('HAVSA',22),\n" +
                    "('İPSALA',22),\n" +
                    "('KEŞAN',22),\n" +
                    "('LALAPAŞA',22),\n" +
                    "('MERİÇ',22),\n" +
                    "('MERKEZ',22),\n" +
                    "('SÜLOĞLU',22),\n" +
                    "('UZUNKÖPRÜ',22),\n" +
                    "('AĞIN',23),\n" +
                    "('ALACAKAYA',23),\n" +
                    "('ARICAK',23),\n" +
                    "('BASKİL',23),\n" +
                    "('KARAKOÇAN',23),\n" +
                    "('KEBAN',23),\n" +
                    "('KOVANCILAR',23),\n" +
                    "('MADEN',23),\n" +
                    "('MERKEZ',23),\n" +
                    "('PALU',23),\n" +
                    "('SİVRİCE',23),\n" +
                    "('ÇAYIRLI',24),\n" +
                    "('İLİÇ',24),\n" +
                    "('KEMAH',24),\n" +
                    "('KEMALİYE',24),\n" +
                    "('MERKEZ',24),\n" +
                    "('OTLUKBELİ',24),\n" +
                    "('REFAHİYE',24),\n" +
                    "('TERCAN',24),\n" +
                    "('ÜZÜMLÜ',24),\n" +
                    "('AŞKALE',25),\n" +
                    "('AZİZİYE',25),\n" +
                    "('ÇAT',25),\n" +
                    "('HINIS',25),\n" +
                    "('HORASAN',25),\n" +
                    "('İSPİR',25),\n" +
                    "('KARAÇOBAN',25),\n" +
                    "('KARAYAZI',25),\n" +
                    "('KÖPRÜKÖY',25),\n" +
                    "('NARMAN',25),\n" +
                    "('OLTU',25),\n" +
                    "('OLUR',25),\n" +
                    "('PALANDÖKEN',25),\n" +
                    "('PASİNLER',25),\n" +
                    "('PAZARYOLU',25),\n" +
                    "('ŞENKAYA',25),\n" +
                    "('TEKMAN',25),\n" +
                    "('TORTUM',25),\n" +
                    "('UZUNDERE',25),\n" +
                    "('YAKUTİYE',25),\n" +
                    "('ALPU',26),\n" +
                    "('BEYLİKOVA',26),\n" +
                    "('ÇİFTELER',26),\n" +
                    "('GÜNYÜZÜ',26),\n" +
                    "('HAN',26),\n" +
                    "('İNÖNÜ',26),\n" +
                    "('MAHMUDİYE',26),\n" +
                    "('MİHALGAZİ',26),\n" +
                    "('MİHALIÇÇIK',26),\n" +
                    "('ODUNPAZARI',26),\n" +
                    "('SARICAKAYA',26),\n" +
                    "('SEYİTGAZİ',26),\n" +
                    "('SİVRİHİSAR',26),\n" +
                    "('TEPEBAŞI',26),\n" +
                    "('ARABAN',27),\n" +
                    "('İSLAHİYE',27),\n" +
                    "('KARKAMIŞ',27),\n" +
                    "('NİZİP',27),\n" +
                    "('NURDAĞI',27),\n" +
                    "('OĞUZELİ',27),\n" +
                    "('ŞAHİNBEY',27),\n" +
                    "('ŞEHİTKAMİL',27),\n" +
                    "('YAVUZELİ',27),\n" +
                    "('ALUCRA',28),\n" +
                    "('BULANCAK',28),\n" +
                    "('ÇAMOLUK',28),\n" +
                    "('ÇANAKÇI',28),\n" +
                    "('DERELİ',28),\n" +
                    "('DOĞANKENT',28),\n" +
                    "('ESPİYE',28),\n" +
                    "('EYNESİL',28),\n" +
                    "('GÖRELE',28),\n" +
                    "('GÜCE',28),\n" +
                    "('KEŞAP',28),\n" +
                    "('MERKEZ',28),\n" +
                    "('PİRAZİZ',28),\n" +
                    "('ŞEBİNKARAHİSAR',28),\n" +
                    "('TİREBOLU',28),\n" +
                    "('YAĞLIDERE',28),\n" +
                    "('KELKİT',29),\n" +
                    "('KÖSE',29),\n" +
                    "('KÜRTÜN',29),\n" +
                    "('MERKEZ',29),\n" +
                    "('ŞİRAN',29),\n" +
                    "('TORUL',29),\n" +
                    "('ÇUKURCA',30),\n" +
                    "('DERECİK',30),\n" +
                    "('MERKEZ',30),\n" +
                    "('ŞEMDİNLİ',30),\n" +
                    "('YÜKSEKOVA',30),\n" +
                    "('ALTINÖZÜ',31),\n" +
                    "('ANTAKYA',31),\n" +
                    "('ARSUZ',31),\n" +
                    "('BELEN',31),\n" +
                    "('DEFNE',31),\n" +
                    "('DÖRTYOL',31),\n" +
                    "('ERZİN',31),\n" +
                    "('HASSA',31),\n" +
                    "('İSKENDERUN',31),\n" +
                    "('KIRIKHAN',31),\n" +
                    "('KUMLU',31),\n" +
                    "('PAYAS',31),\n" +
                    "('REYHANLI',31),\n" +
                    "('SAMANDAĞ',31),\n" +
                    "('YAYLADAĞI',31),\n" +
                    "('ARALIK',76),\n" +
                    "('KARAKOYUNLU',76),\n" +
                    "('MERKEZ',76),\n" +
                    "('TUZLUCA',76),\n" +
                    "('AKSU',32),\n" +
                    "('ATABEY',32),\n" +
                    "('EĞİRDİR',32),\n" +
                    "('GELENDOST',32),\n" +
                    "('GÖNEN',32),\n" +
                    "('KEÇİBORLU',32),\n" +
                    "('MERKEZ',32),\n" +
                    "('SENİRKENT',32),\n" +
                    "('SÜTÇÜLER',32),\n" +
                    "('ŞARKİKARAAĞAÇ',32),\n" +
                    "('ULUBORLU',32),\n" +
                    "('YALVAÇ',32),\n" +
                    "('YENİŞARBADEMLİ',32),\n" +
                    "('ADALAR',34),\n" +
                    "('ARNAVUTKÖY',34),\n" +
                    "('ATAŞEHİR',34),\n" +
                    "('AVCILAR',34),\n" +
                    "('BAĞCILAR',34),\n" +
                    "('BAHÇELİEVLER',34),\n" +
                    "('BAKIRKÖY',34),\n" +
                    "('BAŞAKŞEHİR',34),\n" +
                    "('BAYRAMPAŞA',34),\n" +
                    "('BEŞİKTAŞ',34),\n" +
                    "('BEYKOZ',34),\n" +
                    "('BEYLİKDÜZÜ',34),\n" +
                    "('BEYOĞLU',34),\n" +
                    "('BÜYÜKÇEKMECE',34),\n" +
                    "('ÇATALCA',34),\n" +
                    "('ÇEKMEKÖY',34),\n" +
                    "('ESENLER',34),\n" +
                    "('ESENYURT',34),\n" +
                    "('EYÜPSULTAN',34),\n" +
                    "('FATİH',34),\n" +
                    "('GAZİOSMANPAŞA',34),\n" +
                    "('GÜNGÖREN',34),\n" +
                    "('KADIKÖY',34),\n" +
                    "('KAĞITHANE',34),\n" +
                    "('KARTAL',34),\n" +
                    "('KÜÇÜKÇEKMECE',34),\n" +
                    "('MALTEPE',34),\n" +
                    "('PENDİK',34),\n" +
                    "('SANCAKTEPE',34),\n" +
                    "('SARIYER',34),\n" +
                    "('SİLİVRİ',34),\n" +
                    "('SULTANBEYLİ',34),\n" +
                    "('SULTANGAZİ',34),\n" +
                    "('ŞİLE',34),\n" +
                    "('ŞİŞLİ',34),\n" +
                    "('TUZLA',34),\n" +
                    "('ÜMRANİYE',34),\n" +
                    "('ÜSKÜDAR',34),\n" +
                    "('ZEYTİNBURNU',34),\n" +

                    "('ALİAĞA',35),\n" +
                    "('BALÇOVA',35),\n" +
                    "('BAYINDIR',35),\n" +
                    "('BAYRAKLI',35),\n" +
                    "('BERGAMA',35),\n" +
                    "('BEYDAĞ',35),\n" +
                    "('BORNOVA',35),\n" +
                    "('BUCA',35),\n" +
                    "('ÇEŞME',35),\n" +
                    "('ÇİĞLİ',35),\n" +
                    "('DİKİLİ',35),\n" +
                    "('FOÇA',35),\n" +
                    "('GAZİEMİR',35),\n" +
                    "('GÜZELBAHÇE',35),\n" +
                    "('KARABAĞLAR',35),\n" +
                    "('KARABURUN',35),\n" +
                    "('KARŞIYAKA',35),\n" +
                    "('KEMALPAŞA',35),\n" +
                    "('KINIK',35),\n" +
                    "('KİRAZ',35),\n" +
                    "('KONAK',35),\n" +
                    "('MENDERES',35),\n" +
                    "('MENEMEN',35),\n" +
                    "('NARLIDERE',35),\n" +
                    "('ÖDEMİŞ',35),\n" +
                    "('SEFERİHİSAR',35),\n" +
                    "('SELÇUK',35),\n" +
                    "('TİRE',35),\n" +
                    "('TORBALI',35),\n" +
                    "('URLA',35),\n" +

                    "('AFŞİN',46),\n" +
                    "('ANDIRIN',46),\n" +
                    "('ÇAĞLAYANCERİT',46),\n" +
                    "('DULKADİROĞLU',46),\n" +
                    "('EKİNÖZÜ',46),\n" +
                    "('ELBİSTAN',46),\n" +
                    "('GÖKSUN',46),\n" +
                    "('NURHAK',46),\n" +
                    "('ONİKİŞUBAT',46),\n" +
                    "('PAZARCIK',46),\n" +
                    "('TÜRKOĞLU',46),\n" +

                    "('EFLANİ',78),\n" +
                    "('ESKİPAZAR',78),\n" +
                    "('MERKEZ',78),\n" +
                    "('OVACIK',78),\n" +
                    "('SAFRANBOLU',78),\n" +
                    "('YENİCE',78),\n" +

                    "('AYRANCI',70),\n" +
                    "('BAŞYAYLA',70),\n" +
                    "('ERMENEK',70),\n" +
                    "('KAZIMKARABEKİR',70),\n" +
                    "('MERKEZ',70),\n" +
                    "('SARIVELİLER',70),\n" +

                    "('AKYAKA',36),\n" +
                    "('ARPAÇAY',36),\n" +
                    "('DİGOR',36),\n" +
                    "('KAĞIZMAN',36),\n" +
                    "('MERKEZ',36),\n" +
                    "('SARIKAMIŞ',36),\n" +
                    "('SELİM',36),\n" +
                    "('SUSUZ',36),\n" +

                    "('ABANA',37),\n" +
                    "('AĞLI',37),\n" +
                    "('ARAÇ',37),\n" +
                    "('AZDAVAY',37),\n" +
                    "('BOZKURT',37),\n" +
                    "('CİDE',37),\n" +
                    "('ÇATALZEYTİN',37),\n" +
                    "('DADAY',37),\n" +
                    "('DEVREKANİ',37),\n" +
                    "('DOĞANYURT',37),\n" +
                    "('HANÖNÜ',37),\n" +
                    "('İHSANGAZİ',37),\n" +
                    "('İNEBOLU',37),\n" +
                    "('KÜRE',37),\n" +
                    "('MERKEZ',37),\n" +
                    "('PINARBAŞI',37),\n" +
                    "('SEYDİLER',37),\n" +
                    "('ŞENPAZAR',37),\n" +
                    "('TAŞKÖPRÜ',37),\n" +
                    "('TOSYA',37),\n" +
                    "('AKKIŞLA',38),\n" +
                    "('BÜNYAN',38),\n" +
                    "('DEVELİ',38),\n" +
                    "('FELAHİYE',38),\n" +
                    "('HACILAR',38),\n" +
                    "('İNCESU',38),\n" +
                    "('KOCASİNAN',38),\n" +
                    "('MELİKGAZİ',38),\n" +
                    "('ÖZVATAN',38),\n" +
                    "('PINARBAŞI',38),\n" +
                    "('SARIOĞLAN',38),\n" +
                    "('SARIZ',38),\n" +
                    "('TALAS',38),\n" +
                    "('TOMARZA',38),\n" +
                    "('YAHYALI',38),\n" +
                    "('YEŞİLHİSAR',38),\n" +
                    "('BAHŞILI',71),\n" +
                    "('BALIŞEYH',71),\n" +
                    "('ÇELEBİ',71),\n" +
                    "('DELİCE',71),\n" +
                    "('KARAKEÇİLİ',71),\n" +
                    "('KESKİN',71),\n" +
                    "('MERKEZ',71),\n" +
                    "('SULAKYURT',71),\n" +
                    "('YAHŞİHAN',71),\n" +
                    "('BABAESKİ',39),\n" +
                    "('DEMİRKÖY',39),\n" +
                    "('KOFÇAZ',39),\n" +
                    "('LÜLEBURGAZ',39),\n" +
                    "('MERKEZ',39),\n" +
                    "('PEHLİVANKÖY',39),\n" +
                    "('PINARHİSAR',39),\n" +
                    "('VİZE',39),\n" +
                    "('AKÇAKENT',40),\n" +
                    "('AKPINAR',40),\n" +
                    "('BOZTEPE',40),\n" +
                    "('ÇİÇEKDAĞI',40),\n" +
                    "('KAMAN',40),\n" +
                    "('MERKEZ',40),\n" +
                    "('MUCUR',40),\n" +
                    "('ELBEYLİ',79),\n" +
                    "('MERKEZ',79),\n" +
                    "('MUSABEYLİ',79),\n" +
                    "('POLATELİ',79),\n" +
                    "('BAŞİSKELE',41),\n" +
                    "('ÇAYIROVA',41),\n" +
                    "('DARICA',41),\n" +
                    "('DERİNCE',41),\n" +
                    "('DİLOVASI',41),\n" +
                    "('GEBZE',41),\n" +
                    "('GÖLCÜK',41),\n" +
                    "('İZMİT',41),\n" +
                    "('KANDIRA',41),\n" +
                    "('KARAMÜRSEL',41),\n" +
                    "('KARTEPE',41),\n" +
                    "('KÖRFEZ',41),\n" +
                    "('AHIRLI',42),\n" +
                    "('AKÖREN',42),\n" +
                    "('AKŞEHİR',42),\n" +
                    "('ALTINEKİN',42),\n" +
                    "('BEYŞEHİR',42),\n" +
                    "('BOZKIR',42),\n" +
                    "('CİHANBEYLİ',42),\n" +
                    "('ÇELTİK',42),\n" +
                    "('ÇUMRA',42),\n" +
                    "('DERBENT',42),\n" +
                    "('DEREBUCAK',42),\n" +
                    "('DOĞANHİSAR',42),\n" +
                    "('EMİRGAZİ',42),\n" +
                    "('EREĞLİ',42),\n" +
                    "('GÜNEYSINIR',42),\n" +
                    "('HADİM',42),\n" +
                    "('HALKAPINAR',42),\n" +
                    "('HÜYÜK',42),\n" +
                    "('ILGIN',42),\n" +
                    "('KADINHANI',42),\n" +
                    "('KARAPINAR',42),\n" +
                    "('KARATAY',42),\n" +
                    "('KULU',42),\n" +
                    "('MERAM',42),\n" +
                    "('SARAYÖNÜ',42),\n" +
                    "('SELÇUKLU',42),\n" +
                    "('SEYDİŞEHİR',42),\n" +
                    "('TAŞKENT',42),\n" +
                    "('TUZLUKÇU',42),\n" +
                    "('YALIHÜYÜK',42),\n" +
                    "('YUNAK',42),\n" +
                    "('ALTINTAŞ',43),\n" +
                    "('ASLANAPA',43),\n" +
                    "('ÇAVDARHİSAR',43),\n" +
                    "('DOMANİÇ',43),\n" +
                    "('DUMLUPINAR',43),\n" +
                    "('EMET',43),\n" +
                    "('GEDİZ',43),\n" +
                    "('HİSARCIK',43),\n" +
                    "('MERKEZ',43),\n" +
                    "('PAZARLAR',43),\n" +
                    "('SİMAV',43),\n" +
                    "('ŞAPHANE',43),\n" +
                    "('TAVŞANLI',43),\n" +
                    "('AKÇADAĞ',44),\n" +
                    "('ARAPGİR',44),\n" +
                    "('ARGUVAN',44),\n" +
                    "('BATTALGAZİ',44),\n" +
                    "('DARENDE',44),\n" +
                    "('DOĞANŞEHİR',44),\n" +
                    "('DOĞANYOL',44),\n" +
                    "('HEKİMHAN',44),\n" +
                    "('KALE',44),\n" +
                    "('KULUNCAK',44),\n" +
                    "('PÜTÜRGE',44),\n" +
                    "('YAZIHAN',44),\n" +
                    "('YEŞİLYURT',44),\n" +
                    "('AHMETLİ',45),\n" +
                    "('AKHİSAR',45),\n" +
                    "('ALAŞEHİR',45),\n" +
                    "('DEMİRCİ',45),\n" +
                    "('GÖLMARMARA',45),\n" +
                    "('GÖRDES',45),\n" +
                    "('KIRKAĞAÇ',45),\n" +
                    "('KÖPRÜBAŞI',45),\n" +
                    "('KULA',45),\n" +
                    "('SALİHLİ',45),\n" +
                    "('SARIGÖL',45),\n" +
                    "('SARUHANLI',45),\n" +
                    "('SELENDİ',45),\n" +
                    "('SOMA',45),\n" +
                    "('ŞEHZADELER',45),\n" +
                    "('TURGUTLU',45),\n" +
                    "('YUNUSEMRE',45),\n" +
                    "('ARTUKLU',47),\n" +
                    "('DARGEÇİT',47),\n" +
                    "('DERİK',47),\n" +
                    "('KIZILTEPE',47),\n" +
                    "('MAZIDAĞI',47),\n" +
                    "('MİDYAT',47),\n" +
                    "('NUSAYBİN',47),\n" +
                    "('ÖMERLİ',47),\n" +
                    "('SAVUR',47),\n" +
                    "('YEŞİLLİ',47),\n" +
                    "('AKDENİZ',33),\n" +
                    "('ANAMUR',33),\n" +
                    "('AYDINCIK',33),\n" +
                    "('BOZYAZI',33),\n" +
                    "('ÇAMLIYAYLA',33),\n" +
                    "('ERDEMLİ',33),\n" +
                    "('GÜLNAR',33),\n" +
                    "('MEZİTLİ',33),\n" +
                    "('MUT',33),\n" +
                    "('SİLİFKE',33),\n" +
                    "('TARSUS',33),\n" +
                    "('TOROSLAR',33),\n" +
                    "('YENİŞEHİR',33),\n" +
                    "('BODRUM',48),\n" +
                    "('DALAMAN',48),\n" +
                    "('DATÇA',48),\n" +
                    "('FETHİYE',48),\n" +
                    "('KAVAKLIDERE',48),\n" +
                    "('KÖYCEĞİZ',48),\n" +
                    "('MARMARİS',48),\n" +
                    "('MENTEŞE',48),\n" +
                    "('MİLAS',48),\n" +
                    "('ORTACA',48),\n" +
                    "('SEYDİKEMER',48),\n" +
                    "('ULA',48),\n" +
                    "('YATAĞAN',48),\n" +
                    "('BULANIK',49),\n" +
                    "('HASKÖY',49),\n" +
                    "('KORKUT',49),\n" +
                    "('MALAZGİRT',49),\n" +
                    "('MERKEZ',49),\n" +
                    "('VARTO',49),\n" +
                    "('ACIGÖL',50),\n" +
                    "('AVANOS',50),\n" +
                    "('DERİNKUYU',50),\n" +
                    "('GÜLŞEHİR',50),\n" +
                    "('HACIBEKTAŞ',50),\n" +
                    "('KOZAKLI',50),\n" +
                    "('MERKEZ',50),\n" +
                    "('ÜRGÜP',50),\n" +
                    "('ALTUNHİSAR',51),\n" +
                    "('BOR',51),\n" +
                    "('ÇAMARDI',51),\n" +
                    "('ÇİFTLİK',51),\n" +
                    "('MERKEZ',51),\n" +
                    "('ULUKIŞLA',51),\n" +
                    "('AKKUŞ',52),\n" +
                    "('ALTINORDU',52),\n" +
                    "('AYBASTI',52),\n" +
                    "('ÇAMAŞ',52),\n" +
                    "('ÇATALPINAR',52),\n" +
                    "('ÇAYBAŞI',52),\n" +
                    "('FATSA',52),\n" +
                    "('GÖLKÖY',52),\n" +
                    "('GÜLYALI',52),\n" +
                    "('GÜRGENTEPE',52),\n" +
                    "('İKİZCE',52),\n" +
                    "('KABADÜZ',52),\n" +
                    "('KABATAŞ',52),\n" +
                    "('KORGAN',52),\n" +
                    "('KUMRU',52),\n" +
                    "('MESUDİYE',52),\n" +
                    "('PERŞEMBE',52),\n" +
                    "('ULUBEY',52),\n" +
                    "('ÜNYE',52),\n" +
                    "('BAHÇE',80),\n" +
                    "('DÜZİÇİ',80),\n" +
                    "('HASANBEYLİ',80),\n" +
                    "('KADİRLİ',80),\n" +
                    "('MERKEZ',80),\n" +
                    "('SUMBAS',80),\n" +
                    "('TOPRAKKALE',80),\n" +
                    "('ARDEŞEN',53),\n" +
                    "('ÇAMLIHEMŞİN',53),\n" +
                    "('ÇAYELİ',53),\n" +
                    "('DEREPAZARI',53),\n" +
                    "('FINDIKLI',53),\n" +
                    "('GÜNEYSU',53),\n" +
                    "('HEMŞİN',53),\n" +
                    "('İKİZDERE',53),\n" +
                    "('İYİDERE',53),\n" +
                    "('KALKANDERE',53),\n" +
                    "('MERKEZ',53),\n" +
                    "('PAZAR',53),\n" +
                    "('ADAPAZARI',54),\n" +
                    "('AKYAZI',54),\n" +
                    "('ARİFİYE',54),\n" +
                    "('ERENLER',54),\n" +
                    "('FERİZLİ',54),\n" +
                    "('GEYVE',54),\n" +
                    "('HENDEK',54),\n" +
                    "('KARAPÜRÇEK',54),\n" +
                    "('KARASU',54),\n" +
                    "('KAYNARCA',54),\n" +
                    "('KOCAALİ',54),\n" +
                    "('PAMUKOVA',54),\n" +
                    "('SAPANCA',54),\n" +
                    "('SERDİVAN',54),\n" +
                    "('SÖĞÜTLÜ',54),\n" +
                    "('TARAKLI',54),\n" +
                    "('19 MAYIS',55),\n" +
                    "('ALAÇAM',55),\n" +
                    "('ASARCIK',55),\n" +
                    "('ATAKUM',55),\n" +
                    "('AYVACIK',55),\n" +
                    "('BAFRA',55),\n" +
                    "('CANİK',55),\n" +
                    "('ÇARŞAMBA',55),\n" +
                    "('HAVZA',55),\n" +
                    "('İLKADIM',55),\n" +
                    "('KAVAK',55),\n" +
                    "('LADİK',55),\n" +
                    "('SALIPAZARI',55),\n" +
                    "('TEKKEKÖY',55),\n" +
                    "('TERME',55),\n" +
                    "('VEZİRKÖPRÜ',55),\n" +
                    "('YAKAKENT',55),\n" +
                    "('BAYKAN',56),\n" +
                    "('ERUH',56),\n" +
                    "('KURTALAN',56),\n" +
                    "('MERKEZ',56),\n" +
                    "('PERVARİ',56),\n" +
                    "('ŞİRVAN',56),\n" +
                    "('TİLLO',56),\n" +
                    "('AYANCIK',57),\n" +
                    "('BOYABAT',57),\n" +
                    "('DİKMEN',57),\n" +
                    "('DURAĞAN',57),\n" +
                    "('ERFELEK',57),\n" +
                    "('GERZE',57),\n" +
                    "('MERKEZ',57),\n" +
                    "('SARAYDÜZÜ',57),\n" +
                    "('TÜRKELİ',57),\n" +
                    "('AKINCILAR',58),\n" +
                    "('ALTINYAYLA',58),\n" +
                    "('DİVRİĞİ',58),\n" +
                    "('DOĞANŞAR',58),\n" +
                    "('GEMEREK',58),\n" +
                    "('GÖLOVA',58),\n" +
                    "('GÜRÜN',58),\n" +
                    "('HAFİK',58),\n" +
                    "('İMRANLI',58),\n" +
                    "('KANGAL',58),\n" +
                    "('KOYULHİSAR',58),\n" +
                    "('MERKEZ',58),\n" +
                    "('SUŞEHRİ',58),\n" +
                    "('ŞARKIŞLA',58),\n" +
                    "('ULAŞ',58),\n" +
                    "('YILDIZELİ',58),\n" +
                    "('ZARA',58),\n" +
                    "('AKÇAKALE',63),\n" +
                    "('BİRECİK',63),\n" +
                    "('BOZOVA',63),\n" +
                    "('CEYLANPINAR',63),\n" +
                    "('EYYÜBİYE',63),\n" +
                    "('HALFETİ',63),\n" +
                    "('HALİLİYE',63),\n" +
                    "('HARRAN',63),\n" +
                    "('HİLVAN',63),\n" +
                    "('KARAKÖPRÜ',63),\n" +
                    "('SİVEREK',63),\n" +
                    "('SURUÇ',63),\n" +
                    "('VİRANŞEHİR',63),\n" +
                    "('BEYTÜŞŞEBAP',73),\n" +
                    "('CİZRE',73),\n" +
                    "('GÜÇLÜKONAK',73),\n" +
                    "('İDİL',73),\n" +
                    "('MERKEZ',73),\n" +
                    "('SİLOPİ',73),\n" +
                    "('ULUDERE',73),\n" +
                    "('ÇERKEZKÖY',59),\n" +
                    "('ÇORLU',59),\n" +
                    "('ERGENE',59),\n" +
                    "('HAYRABOLU',59),\n" +
                    "('KAPAKLI',59),\n" +
                    "('MALKARA',59),\n" +
                    "('MARMARAEREĞLİSİ',59),\n" +
                    "('MURATLI',59),\n" +
                    "('SARAY',59),\n" +
                    "('SÜLEYMANPAŞA',59),\n" +
                    "('ŞARKÖY',59),\n" +
                    "('ALMUS',60),\n" +
                    "('ARTOVA',60),\n" +
                    "('BAŞÇİFTLİK',60),\n" +
                    "('ERBAA',60),\n" +
                    "('MERKEZ',60),\n" +
                    "('NİKSAR',60),\n" +
                    "('PAZAR',60),\n" +
                    "('REŞADİYE',60),\n" +
                    "('SULUSARAY',60),\n" +
                    "('TURHAL',60),\n" +
                    "('YEŞİLYURT',60),\n" +
                    "('ZİLE',60),\n" +
                    "('AKÇAABAT',61),\n" +
                    "('ARAKLI',61),\n" +
                    "('ARSİN',61),\n" +
                    "('BEŞİKDÜZÜ',61),\n" +
                    "('ÇARŞIBAŞI',61),\n" +
                    "('ÇAYKARA',61),\n" +
                    "('DERNEKPAZARI',61),\n" +
                    "('DÜZKÖY',61),\n" +
                    "('HAYRAT',61),\n" +
                    "('KÖPRÜBAŞI',61),\n" +
                    "('MAÇKA',61),\n" +
                    "('OF',61),\n" +
                    "('ORTAHİSAR',61),\n" +
                    "('SÜRMENE',61),\n" +
                    "('ŞALPAZARI',61),\n" +
                    "('TONYA',61),\n" +
                    "('VAKFIKEBİR',61),\n" +
                    "('YOMRA',61),\n" +
                    "('ÇEMİŞGEZEK',62),\n" +
                    "('HOZAT',62),\n" +
                    "('MAZGİRT',62),\n" +
                    "('MERKEZ',62),\n" +
                    "('NAZIMİYE',62),\n" +
                    "('OVACIK',62),\n" +
                    "('PERTEK',62),\n" +
                    "('PÜLÜMÜR',62),\n" +
                    "('BANAZ',64),\n" +
                    "('EŞME',64),\n" +
                    "('KARAHALLI',64),\n" +
                    "('MERKEZ',64),\n" +
                    "('SİVASLI',64),\n" +
                    "('ULUBEY',64),\n" +
                    "('BAHÇESARAY',65),\n" +
                    "('BAŞKALE',65),\n" +
                    "('ÇALDIRAN',65),\n" +
                    "('ÇATAK',65),\n" +
                    "('EDREMİT',65),\n" +
                    "('ERCİŞ',65),\n" +
                    "('GEVAŞ',65),\n" +
                    "('GÜRPINAR',65),\n" +
                    "('İPEKYOLU',65),\n" +
                    "('MURADİYE',65),\n" +
                    "('ÖZALP',65),\n" +
                    "('SARAY',65),\n" +
                    "('TUŞBA',65),\n" +
                    "('ALTINOVA',77),\n" +
                    "('ARMUTLU',77),\n" +
                    "('ÇINARCIK',77),\n" +
                    "('ÇİFTLİKKÖY',77),\n" +
                    "('MERKEZ',77),\n" +
                    "('TERMAL',77),\n" +
                    "('AKDAĞMADENİ',66),\n" +
                    "('AYDINCIK',66),\n" +
                    "('BOĞAZLIYAN',66),\n" +
                    "('ÇANDIR',66),\n" +
                    "('ÇAYIRALAN',66),\n" +
                    "('ÇEKEREK',66),\n" +
                    "('KADIŞEHRİ',66),\n" +
                    "('MERKEZ',66),\n" +
                    "('SARAYKENT',66),\n" +
                    "('SARIKAYA',66),\n" +
                    "('SORGUN',66),\n" +
                    "('ŞEFAATLİ',66),\n" +
                    "('YENİFAKILI',66),\n" +
                    "('YERKÖY',66),\n" +
                    "('ALAPLI',67),\n" +
                    "('ÇAYCUMA',67),\n" +
                    "('DEVREK',67),\n" +
                    "('EREĞLİ',67),\n" +
                    "('GÖKÇEBEY',67),\n" +
                    "('KİLİMLİ',67),\n" +
                    "('KOZLU',67),\n" +
                    "('MERKEZ',67);";

             MainActivity.db.execSQL(sqlQueryDistrict);
        }
    }
}
